server:
  port: 8282
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanagement
    username: fawry
    password: fawry
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true